export enum ENVIRONMENT {
  MONGODB_URL = 'MONGODB_URL',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  DB_NAME = 'DB_NAME',
  CORS_ORIGIN = 'CORS_ORIGIN',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}
